Update Dockerfile.dev

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -31,19 +31,17 @@ RUN sed --in-place "s*CODENAME_SUBSTITUTE*$CODENAME*g" /etc/apt/preferences.d/90
 # [1] https://github.com/phusion/baseimage-docker/issues/58
 RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 
+# Enable additional architectures for cross-compilation
+RUN dpkg --add-architecture arm64
+
 # Refresh the apt package metadata
 RUN apt-get update
 
-# Install QEMU user static for cross-compilation support
-RUN apt-get install --yes qemu-user-static binfmt-support
-
+# Install base dependencies first
 RUN apt-get install --yes \
                           # Install required dependencies for the build
                           make rsync sudo debootstrap squashfs-tools xorriso git git-lfs gettext \
                           dosfstools mtools checkinstall cmake time \
-                          # UEFI boot components (both x86_64 and ARM64)
-                          shim-signed grub-efi-amd64-signed grub-efi-amd64-bin grub-efi-ia32-bin \
-                          grub-efi-arm64 grub-efi-arm64-bin grub-efi-arm64-signed grub-pc-bin \
                           devscripts debhelper ccache \
                           # Dependencies for "sfdisk" and "partclone.restore" build
                           libtool-bin gawk pkg-config comerr-dev docbook-xsl e2fslibs-dev fuse3 \
@@ -55,11 +53,28 @@ RUN apt-get install --yes \
                           # Cross-compilation toolchains for multiple architectures
                           gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
                           libc6-dev-arm64-cross \
-                          gcc-x86-64-linux-gnu g++-x86-64-linux-gnu \
                           # Select runtime dependencies required for running the unit tests
                           python3-gi libgtk-3-dev python3-whichcraft python3-babel \
                           # Install optional dependencies for quality-of-life when debugging
                           tmux vim
+
+# Install x86_64 GRUB packages (these work on x86_64 host)
+RUN apt-get install --yes --no-install-recommends \
+                          shim-signed grub-efi-amd64-signed grub-efi-amd64-bin \
+                          grub-efi-ia32-bin grub-pc-bin
+
+# Try to install ARM64 GRUB packages, but don't fail if they're not available
+RUN apt-get install --yes --no-install-recommends \
+                          grub-efi-arm64 || echo "grub-efi-arm64 not available, will be handled during ISO build"
+
+RUN apt-get install --yes --no-install-recommends \
+                          grub-efi-arm64-bin || echo "grub-efi-arm64-bin not available, will be handled during ISO build"
+
+RUN apt-get install --yes --no-install-recommends \
+                          grub-efi-arm64-signed || echo "grub-efi-arm64-signed not available, will be handled during ISO build"
+
+# Install QEMU user static for emulation support (if needed during build)
+RUN apt-get install --yes qemu-user-static binfmt-support
 
 # Set up cross-compilation environment variables
 ENV CC_FOR_TARGET=aarch64-linux-gnu-gcc
@@ -67,6 +82,10 @@ ENV CXX_FOR_TARGET=aarch64-linux-gnu-g++
 ENV AR_FOR_TARGET=aarch64-linux-gnu-ar
 ENV STRIP_FOR_TARGET=aarch64-linux-gnu-strip
 ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
+ENV ARCH=arm64
+
+# Clean up apt cache to reduce image size
+RUN apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Restore interactivity of package installation within Docker
 RUN echo 'debconf debconf/frontend select Dialog' | debconf-set-selections
